from .db import get_connection

LITHOLOGY_ENCODING = {
    "ARCHAEAN-PROTEROZOIC | SOUTHERN GRANULITE TERRAIN | MIGMATITE | BIOTITE GNEISS": 0,
    "ARCHAEAN-PROTEROZOIC | SOUTHERN GRANULITE TERRAIN | CHARNOCKITE | ACID TO INTERMEDIATE CHARNOCKITE": 1,
    "ARCHAEAN-PROTEROZOIC | SOUTHERN GRANULITE TERRAIN | MIGMATITE | PINK GRANITE GNEISS": 2,
    "ARCHAEAN-PROTEROZOIC | SOUTHERN GRANULITE TERRAIN | MIGMATITE | HORNBLENDE-BIOTITE GNEISS": 3,
    "MEGHALAYAN | SOUTHERN GRANULITE TERRAIN | ACTIVE FLUVIAL DEPOSIT | CLAYEY SAND (ACTIVE FLOODPLAIN)": 4,
    "NEOPROTEROZOIC | SOUTHERN GRANULITE TERRAIN | MIGMATITE | GRANITE": 5,
    "ARCHAEAN-PROTEROZOIC | SOUTHERN GRANULITE TERRAIN | CHARNOCKITE | PYROXENE GRANULITE": 6,
    "ARCHAEAN | SOUTHERN GRANULITE TERRAIN | WYANAD | BANDED IRON FORMATION": 7,
    "ARCHAEAN-PROTEROZOIC | SOUTHERN GRANULITE TERRAIN | KHONDALITE | GAR-BIO-SILL GNEISS + GRAPHITE + KYANITE": 8,
    "NEOPROTEROZOIC | SOUTHERN GRANULITE TERRAIN | MIGMATITE | PEGMATITE": 9,
    "ARCHAEAN-PROTEROZOIC | SOUTHERN GRANULITE TERRAIN | KHONDALITE | QUARTZITE": 10,
    "MESOZOIC | SOUTHERN GRANULITE TERRAIN | MIGMATITE | GABBRO": 11,
}

def get_lithology(lat: float, lon: float):
    conn = get_connection()
    cur = conn.cursor()
    cur.execute("""
        SELECT "AGE", "SUPERGROUP", "GROUP_NAME", "LITHOLOGIC"
        FROM "ALPS"."LITHOLOGY"
        WHERE ST_Contains(geom, ST_SetSRID(ST_Point(%s, %s), 4326))
        ORDER BY ST_Area(geom) ASC
        LIMIT 1;
    """, (lon, lat))
    result = cur.fetchone()
    cur.close()
    conn.close()

    if result:
        formatted = " | ".join(result)
        print(formatted)
        return LITHOLOGY_ENCODING.get(formatted, None)
    return None